### PR TITLE
Make pax-exam-helper smarter by automatically resolving transitive dependencies

### PR DESCRIPTION
**Pull request by bertfrees**
...using the Sonatype Aether library. For this to work all runtime
dependencies must be declared in the POMs. Thanks to this change the
pax-exam-helper will work with any (future) version of the
Pipeline. Therefore it is no use anymore that the version number matches
the main Pipeline version.

### CODE REVIEW

**Comment by bertfrees** [comment]
Maybe I can test it some more before you merge? I've only used it in https://github.com/daisy/pipeline-clientlib-java/pull/10 so far.

**Comment by josteinaj** [comment]
This branch doesn't build for me:

```
➜  pax-exam-helper git:(6c83478) mvn clean test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building DAISY Pipeline 2 :: Pax Exam Helper 2.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pax-exam-helper ---
[INFO] Deleting /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-maven) @ pax-exam-helper ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ pax-exam-helper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ pax-exam-helper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/target/classes
[WARNING] /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java: /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java uses or overrides a deprecated API.
[WARNING] /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/src/main/java/org/daisy/pipeline/pax/exam/Options.java: Recompile with -Xlint:deprecation for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ pax-exam-helper ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ pax-exam-helper ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.16:test (default-test) @ pax-exam-helper ---
[INFO] Surefire report directory: /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.daisy.pipeline.pax.exam.OptionsTest
18:57:40.793 [main] INFO  org.daisy.pipeline.pax.exam.Options - mavenBundlesWithDependencies(
	mavenBundle("ch.qos.logback:logback-classic:1.0.11"))
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.264 sec <<< FAILURE! - in org.daisy.pipeline.pax.exam.OptionsTest
testLogbackClassicWithDependencies(org.daisy.pipeline.pax.exam.OptionsTest)  Time elapsed: 0.227 sec  <<< ERROR!
java.lang.RuntimeException: org.sonatype.aether.resolution.DependencyResolutionException: The repository system is offline but the artifact org.slf4j:slf4j-api:jar:1.7.4 is not available in the local repository.
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:348)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.getBundles(Options.java:333)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.<init>(Options.java:304)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.<init>(Options.java:292)
	at org.daisy.pipeline.pax.exam.Options.mavenBundlesWithDependencies(Options.java:289)
	at org.daisy.pipeline.pax.exam.OptionsTest.testLogbackClassicWithDependencies(OptionsTest.java:20)


Results :

Tests in error: 
  OptionsTest.testLogbackClassicWithDependencies:20 » Runtime org.sonatype.aethe...

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.306 s
[INFO] Finished at: 2015-12-08T18:57:40+01:00
[INFO] Final Memory: 22M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.16:test (default-test) on project pax-exam-helper: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/jostein/daisy-pipeline/pipeline-build-utils/pax-exam-helper/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by bertfrees** [comment]
OK try again.

**Comment by josteinaj** [comment]
Nope:

```
testLogbackClassicWithDependencies(org.daisy.pipeline.pax.exam.OptionsTest)  Time elapsed: 0.222 sec  <<< ERROR!
java.lang.RuntimeException: org.sonatype.aether.resolution.DependencyResolutionException: Could not transfer artifact org.slf4j:slf4j-api:jar:1.7.4 from/to central (http://repo.maven.apache.org/maven2): No connector available to access repository central (http://repo.maven.apache.org/maven2) of type default using the available factories 
	at org.sonatype.aether.impl.internal.DefaultRemoteRepositoryManager.getRepositoryConnector(DefaultRemoteRepositoryManager.java:400)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:453)
	at org.sonatype.aether.impl.internal.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:216)
	at org.sonatype.aether.impl.internal.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:358)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.getBundles(Options.java:333)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.<init>(Options.java:304)
	at org.daisy.pipeline.pax.exam.Options$MavenBundlesWithDependencies.<init>(Options.java:292)
	at org.daisy.pipeline.pax.exam.Options.mavenBundlesWithDependencies(Options.java:289)
	at org.daisy.pipeline.pax.exam.OptionsTest.testLogbackClassicWithDependencies(OptionsTest.java:20)
```

**Comment by bertfrees** [comment]
Hmm, right. I think I need some other libraries to take care of the downloading. The other solution is that you add all the artifacts that are in the test as (test) dependencies in the POM (in this case `pax-exam-helper/pom.xml`). This is what will be the case almost always and that was also the reason I had set the repository system to "offline" in the first place. You can try that in the meantime if you want to continue using this for https://github.com/daisy/pipeline-clientlib-java/pull/10 and can't wait for a fix.

**Comment by josteinaj** [comment]
I can wait for a fix instead.

**Comment by bertfrees** [comment]
OK now I think I fixed it.

**Comment by josteinaj** [comment]
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] DAISY Pipeline 2 :: Modules Parent POM ............. SUCCESS [  0.244 s]
[INFO] DAISY Pipeline 2 :: Modules Build Helper ........... SUCCESS [  0.551 s]
[INFO] DAISY Pipeline 2 :: Adapter for Saxon .............. SUCCESS [  1.069 s]
[INFO] DAISY Pipeline 2 :: Pax Exam Helper ................ SUCCESS [ 33.955 s]
[INFO] DAISY Pipeline 2 archetype :: Basic module ......... SUCCESS [  1.458 s]
[INFO] Pipeline Build Utils Aggregator for Archetypes ..... SUCCESS [  0.073 s]
[INFO] Pipeline Build Utils Aggregator .................... SUCCESS [  0.003 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 37.904 s
[INFO] Finished at: 2016-01-15T13:41:13+01:00
[INFO] Final Memory: 40M/466M
[INFO] ------------------------------------------------------------------------
```

yes! :)

**Comment by bertfrees** [comment]
@rdeltour I have rebased on master and staged version 2.0.0.

**Pull request merged**
