### PR TITLE
clientlib-java-jabx

### PR DESCRIPTION
**Pull request by bertfrees**
Depends on:
- [x] https://github.com/daisy/pipeline-build-utils/pull/33

### CODE REVIEW

**Comment by bertfrees** [comment]
I'm moving it because of https://github.com/daisy/pipeline-tasks/issues/67.

**Comment by rdeltour** [comment]
> I'm moving it because of daisy/pipeline-tasks#67.

Right. when I wrote the comment I thought it was moved from `pipeline-clientlib-java`, which looked like a more natural place. But of course it makes sense to move it out of `pipeline-it`. LGTM.

**Comment by bertfrees** [comment]
Yep. Actually the original idea was to merge it with pipeline-clientlib-java.

**Comment by bertfrees** [comment]
Fixed in e87e750

**Pull request closed without merging**
